### ISSUE TITLE
Would you publish the source code of  swc

### ISSUE THREAD

**Issue by AdamSun** [MTeamCo/UnicodeRTL#1]
Hi,it is grateful that you do this great job,this project is useful for us,we are developping an app using Farsi.I wonder if you could publish the source code of swc file,We want to merge this to our Starling project.Thanks a lot!!!

**Comment by MESepehr** [comment]
Hello AdamSun,
Ok! we did it for you: 
https://github.com/SaffronCode/UnicodeRTL/tree/master/developer_source
Have fun!

We are currently planing to release a framework for Adobe Animate named [SaffronCode ](https://github.com/SaffronCode/SaffronCode) and that UnicodeRTL is a small package of it's private part. we would be happy if you support us with your [stars](https://github.com/SaffronCode/SaffronCode/stargazers) for the main framework to help us make it open source.

**Comment by AdamSun** [comment]
Hi, MESepehr, Thanks a lot! SaffronCode is an amazing framework!
