### ISSUE TITLE
typeing arabic word inside input text field  on andriod phone not correclty 

### ISSUE THREAD

**Issue by moazatiani** [MTeamCo/UnicodeRTL#2]
hi , how to correctly  typing Arabic word inside input text field  on android phone

**Comment by MESepehr** [comment]
Hello Moazatiani,
You could use flash.text.StageText to get user's Arabic inputs. by the way, we have other component that doesn't come in public. it perfectly works with default TextFiels of the Flash and Adobe Animate, that brings more functionalities as you can see bellow. 

> public static function setUp(textField:TextField,softKeyFormat:String = SoftKeyboardType.DEFAULT,convertArabic:Boolean=true,correctingArabicNumbers:Boolean = true,clearAfterClicked:Boolean = false,justShowNativeText:Boolean=false,editableNative:Boolean=true,controllStageChangesTo:Boolean=true,ReturnLable:String=ReturnKeyLabel.DEFAULT,onDoneFunction:Function=null)

 If you think that could comes handy for you, you can contact me via Email.
